name: DrosP_code
channels:
  - anaconda
dependencies:
  - python=3.8
  - jupyter
  - pip 
  - pip:
      - tensorflow==2.8.4
      - sleap[pypi]==1.3.3
      - tables
      - openpyxl
      - tqdm
      - seaborn==0.13.2
