# %%
import numpy as np

# %%


class wormstats:
    def __init__(self):
        fixed_length = 60  # You can adjust this based on your data

        self.traj_timeseries = np.dtype(
            [
                ("head_vel", "<f8"),
                ("thorax_vel", "<f8"),
                ("abdomen_vel", "<f8"),
                ("wingL_vel", "<f8"),
                ("wingR_vel", "<f8"),
                ("head_angular_vel", "<f8"),
                ("thorax_angular_vel", "<f8"),
                ("abdomen_angular_vel", "<f8"),
                ("wingL_angular_vel", "<f8"),
                ("wingR_angular_vel", "<f8"),
                ("fly_ID", "<i8"),
                ("frame_number", "<i8"),
                ("cabinet", f"S{fixed_length}"),
                ("shelf number", f"S{fixed_length}"),
                ("plate number", f"S{fixed_length}"),
                ("well number", f"S{fixed_length}"),
                ("Date_yyyy-mm-dd", f"S{fixed_length}"),
                ("fly_type", f"S{fixed_length}"),
                ("concentration (ppm)", "<i8"),
                ("hour", "<i8"),
                ("CSN", f"S{fixed_length}"),
                ("ISN", f"S{fixed_length}"),
                ("genotype", f"S{fixed_length}"),
                ("barcode", "<i8"),
                ("motion_mode", "<f8"),
            ]
        )

        # np.dtype(
        #     [
        #         ("head_vel [mms]", "<f8"),
        #         ("thorax_vel[mms]", "<f8"),
        #         ("abdomen_vel[mms]", "<f8"),
        #         ("wingL_vel[mms]", "<f8"),
        #         ("wingR_vel[mms]", "<f8"),
        #         ("fly_ID", "<i8"),
        #         ("frame_number", "<i8"),
        #         ("cabinet", f"S{fixed_length}"),  # Replace 'O' with fixed-length string
        #         ("shelf number", f"S{fixed_length}"),
        #         ("plate number", f"S{fixed_length}"),
        #         ("well number", f"S{fixed_length}"),
        #         ("Dateyyyy-mm-dd", f"S{fixed_length}"),
        #         ("fly_type", f"S{fixed_length}"),
        #         ("concentration (ppm)", "<i8"),
        #         ("hour", "<i8"),
        #         ("CSN", f"S{fixed_length}"),
        #         ("ISN", f"S{fixed_length}"),
        #         ("genotype", f"S{fixed_length}"),
        #         ("barcode", "<i8"),
        #     ]
        # )

        self.feat_summary = np.dtype(
            [
                ("head_vel_50th_abs", "<f8"),
                ("thorax_vel_50th_abs", "<f8"),
                ("abdomen_vel_50th_abs", "<f8"),
                ("wingL_vel_50th_abs", "<f8"),
                ("wingR_vel_50th_abs", "<f8"),
                ("head_angular_vel_50th_abs", "<f8"),
                ("thorax_angular_vel_50th_abs", "<f8"),
                ("abdomen_angular_vel_50th_abs", "<f8"),
                ("wingL_angular_vel_50th_abs", "<f8"),
                ("wingR_angular_vel_50th_abs", "<f8"),
                ("motion_mode_fraction", "<f8"),
                ("head_vel_50th_abs_w_pause", "<f8"),
                ("thorax_vel_50th_abs_w_pause", "<f8"),
                ("abdomen_vel_50th_abs_w_pause", "<f8"),
                ("wingL_vel_50th_abs_w_pause", "<f8"),
                ("wingR_vel_50th_abs_w_pause", "<f8"),
                ("head_angular_vel_50th_abs_w_pause", "<f8"),
                ("thorax_angular_vel_50th_abs_w_pause", "<f8"),
                ("abdomen_angular_vel_50th_abs_w_pause", "<f8"),
                ("wingL_angular_vel_50th_abs_w_pause", "<f8"),
                ("wingR_angular_vel_50th_abs_w_pause", "<f8"),
                ("fly_ID", f"S{fixed_length}"),
                ("cabinet", f"S{fixed_length}"),
                ("shelf number", f"S{fixed_length}"),
                ("plate number", f"S{fixed_length}"),
                ("well number", f"S{fixed_length}"),
                ("Date_yyyy-mm-dd", f"S{fixed_length}"),
                ("fly_type", f"S{fixed_length}"),
                ("concentration (ppm)", "<i8"),
                ("hour", "<i8"),
                ("CSN", f"S{fixed_length}"),
                ("ISN", f"S{fixed_length}"),
                ("genotype", f"S{fixed_length}"),
                ("barcode", "<i8"),
            ]
        )

        #  ("head_mean_vel[mms]", "<f8"),
        #         ("thorax_mean_vel[mms]", "<f8"),
        #         ("abdomen_mean_vel[mms]", "<f8"),
        #         ("wingL_mean_vel[mms]", "<f8"),
        #         ("wingR_mean_vel[mms]", "<f8"),
        #         ("cabinet", f"S{fixed_length}"),
        #         ("shelf number", f"S{fixed_length}"),
        #         ("plate number", f"S{fixed_length}"),
        #         ("well number", f"S{fixed_length}"),
        #         ("Date yyyy-mm-dd", f"S{fixed_length}"),
        #         ("fly_type", f"S{fixed_length}"),
        #         ("concentration (ppm)", "<i8"),
        #         ("hour", "<i8"),
        #         ("CSN", f"S{fixed_length}"),
        #         ("ISN", f"S{fixed_length}"),
        #         ("genotype", f"S{fixed_length}"),
        #         ("barcode", "<i8"),
        self.init_col_time_series = [
            "head_vel",
            "thorax_vel",
            "abdomen_vel",
            "wingL_vel",
            "wingR_vel",
            "head_angular_vel",
            "thorax_angular_vel",
            "abdomen_angular_vel",
            "wingL_angular_vel",
            "wingR_angular_vel",
            "fly_ID",
            "frame_number",
            "cabinet",
            "shelf number",
            "plate number",
            "well number",
            "Date_yyyy-mm-dd",
            "fly_type",
            "concentration (ppm)",
            "hour",
            "CSN",
            "ISN",
            "genotype",
            "barcode",
        ]
        self.init_col_fet_summ = [
            "head_vel_50th_abs",
            "thorax_vel_50th_abs",
            "abdomen_vel_50th_abs",
            "wingL_vel_50th_abs",
            "wingR_vel_50th_abs",
            "head_angular_vel_50th_abs",
            "thorax_angular_vel_50th_abs",
            "abdomen_angular_vel_50th_abs",
            "wingL_angular_vel_50th_abs",
            "wingR_angular_vel_50th_abs",
            "motion_mode_fraction",
            "head_vel_50th_abs_w_pause",
            "thorax_vel_50th_abs_w_pause",
            "abdomen_vel_50th_abs_w_pause",
            "wingL_vel_50th_abs_w_pause",
            "wingR_vel_50th_abs_w_pause",
            "head_angular_vel_50th_abs_w_pause",
            "thorax_angular_vel_50th_abs_w_pause",
            "abdomen_angular_vel_50th_abs_w_pause",
            "wingL_angular_vel_50th_abs_w_pause",
            "wingR_angular_vel_50th_abs_w_pause",
        ]
